### ISSUE TITLE
有测试吗？猫影视的配置，现在完全没用

### ISSUE THREAD

**Issue by MINGERTAI** [jadehh/TVSpider#101]
有测试吗？猫影视的配置，现在完全没用，刚测试了tvbox也没用

**Comment by jadehh** [comment]
贴上自己的源呢，具体哪个不能用还是都不能用，而且我看拉取请求都是你的，不要往这个仓库推，往自己的私仓推，TV Box可以直接使用我这边的config, 我这边测试都是正常的。

**Comment by jadehh** [comment]
截个图看下呢，是源都没有加载出来，还是能加载出来源，分类页和首页加载不出来。可以尝试下清空缓存。

**Comment by jadehh** [comment]
![image](https://github.com/jadehh/TVSpider/assets/20532462/760a9fd2-78fc-4607-9aaf-a91a51244532)

**Comment by MINGERTAI** [comment]
非常感谢
<img width="707" alt="微信图片_20240506182618" src="https://github.com/jadehh/TVSpider/assets/104557080/5974c905-339a-4383-ac14-cb93a239b75b">
<img width="707" alt="微信图片_20240506182657" src="https://github.com/jadehh/TVSpider/assets/104557080/6a6ceb86-52a0-4e54-8b20-ff6fcec43748">
<img width="811" alt="微信图片_20240506182706" src="https://github.com/jadehh/TVSpider/assets/104557080/79e96c60-68cd-49a5-95bc-2e1f526c6b44">

**Comment by jadehh** [comment]
都打个包 dist 分之➕你的版本，我本地给你测下。

**Comment by MINGERTAI** [comment]
非常感谢，是我的问题！您的提醒清空缓存，清空缓存就没问题了。谢谢了
