### ISSUE TITLE
不支持takagen99 

### ISSUE THREAD

**Issue by MINGERTAI** [jadehh/TVSpider#117]
测试不支持[takagen99](https://github.com/takagen99/Box)

所有源都如下图

猫影视，支持非常完美

**Comment by MINGERTAI** [comment]
![微信图片_20240511191002](https://github.com/jadehh/TVSpider/assets/104557080/7877e8a5-f6d4-4d5a-b2f5-fa99ab7e1c91)

**Comment by jadehh** [comment]
用 影视 tv 吧，暂时不考虑其他的
