### ISSUE TITLE
玩偶哥哥无法打开详情页面

### ISSUE THREAD

**Issue by xhybb** [jadehh/TVSpider#122]
![image](https://github.com/jadehh/TVSpider/assets/19210186/b5034f71-49c0-464e-a0d6-aa7dfad874f5)

**Comment by jadehh** [comment]
这应该是分享链接没了。

**Comment by clear2x** [comment]
好像是玩偶的域名改了

**Comment by hanc44** [comment]
域名后缀改一下就行了
