### ISSUE TITLE
是我哪里做的不对吗

### ISSUE THREAD

**Issue by sds612401** [jadehh/TVSpider#136]
![IMG_20240528_002720](https://github.com/jadehh/TVSpider/assets/90450912/c9b800a9-2ff2-4ab8-9e2b-53d05cd90bf2)
![IMG_20240528_002731](https://github.com/jadehh/TVSpider/assets/90450912/db782098-bfc8-4ad6-90dc-68869992514a)
![IMG_20240528_002747](https://github.com/jadehh/TVSpider/assets/90450912/56efbb44-9fe7-4d30-99f4-86235d6b086c)
![IMG_20240528_002839_edit_939085743620248](https://github.com/jadehh/TVSpider/assets/90450912/dc6fb8fa-37b6-412b-98de-ed4f058553f4)
![Screenshot_20240528_003340_com github catvod app_edit_939380293178016](https://github.com/jadehh/TVSpider/assets/90450912/23494c33-be7f-42d6-bdb5-4823417b02e5)
是我哪里没弄好还是怎么回事，，站源数据还是为空，阿里，夸克还有哔哩我都改掉了，怎么还是不行呢，求解

**Comment by jadehh** [comment]
看下猫的版本呢

**Comment by sds612401** [comment]
![Uploading Screenshot_20240528_004413_com.github.catvod.app.jpg…]()

**Comment by jadehh** [comment]
你这个地址有问题吧，主分之是main

**Comment by sds612401** [comment]
> 看看猫的版本呢

![Uploading Screenshot_20240528_004413_com.github.catvod.app.jpg…]()

**Comment by sds612401** [comment]
> 你这个地址有问题吧，主要原因是

那我要如何配置地址呢

**Comment by jadehh** [comment]
clone一个设置成开源我看下。

**Comment by jadehh** [comment]
SDS/main/mys/接后面的路径

**Comment by sds612401** [comment]
> 克隆一个设置并将其开源到我下面。

我不会克隆 我还是个新手，有些东西我还不太懂，https://github.com/sds612401/mys.git这是那个文件的url

**Comment by jadehh** [comment]
参考下[wikis](https://github.com/jadehh/TVSpider/wiki/TV-Spider-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)

**Comment by sds612401** [comment]
大佬，我不会弄，教教我配置猫影视的接口吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 上午9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jadehh/TVSpider] 是我哪里做的不对吗 (Issue #136)














 
参考下wikis

**Comment by sds612401** [comment]
> 参考[wikis](https://github.com/jadehh/TVSpider/wiki/TV-Spider-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)

我能不能加你qq，你详细的教一下我，我才接触这个，有的地方还不会弄，可以加你吗？打扰大佬了。

**Comment by jadehh** [comment]
加V吧
<img src="https://github.com/jadehh/TVSpider/assets/20532462/8ac28720-5869-470a-91ad-d2a2d2941228" alt="image-20240524134521207.png" width=320 height=480  />

**Comment by mzlipro** [comment]
不懂这个，还不如直接用坚果云的webdav弄
