### ISSUE TITLE
ios的怎么解决

### ISSUE THREAD

**Issue by sds612401** [jadehh/TVSpider#138]
![mmexport1717180037369](https://github.com/jadehh/TVSpider/assets/90450912/e145003c-d176-428e-8086-ffbc4937ac90)
是我下载的版本不对吗？我下载的是ios_open_1.1.4_preview5.ipa 这个版本，求解惑

**Comment by mzlipro** [comment]
看看这个吧，看底部的关于安装部分的说明https://omii.top/813.html
