### ISSUE TITLE
CatVodOpen_1.1.3_preview3全部源加载失败

### ISSUE THREAD

**Issue by xhybb** [jadehh/TVSpider#17]
CatVodOpen_1.1.3_preview3删除了quickjs 运行时，所有源都加载失败，麻烦大佬适配新版本 Node.js运行时。

**Comment by jadehh** [comment]
有供测试的源吗

**Comment by jadehh** [comment]
这样的话，就无法适配TV了，现在TV和catvodopen是一套代码的

发自我的 iPhone

在 2024年3月20日，20:20，xhybb ***@***.***> 写道：

﻿

CatVodOpen_1.1.3_preview3删除了quickjs 运行时，所有源都加载失败，麻烦大佬适配新版本 Node.js运行时。

**Comment by xhybb** [comment]
Node.js版本需要编译源才能使用，https://github.com/catvod/CatVodOpen/tree/main/nodejs

**Comment by jadehh** [comment]
## TODO
- [X] 已完成酷云77移植
- [X] 已完成一起看App移植
- [] 后续完成阿里系列的移植
