### ISSUE TITLE
360 荐片 都播放失败

### ISSUE THREAD

**Issue by woshishiq1** [jadehh/TVSpider#40]
能修吗

**Comment by jadehh** [comment]
影视TV是支持360的，猫影视后面在考虑修复吧

**Comment by woshishiq1** [comment]
我有猫能播放的360,你要借鉴下吗！ 别人发我的 , 不过他那是通过服务器搭建的解析解析360影片！ 我可以把他服务器地址删了 然后发给你借鉴下 看能修改成直接通过填写第三方解析播放不，需要的话发一下联系方式

**Comment by jadehh** [comment]
后面考虑把这些线路加入猫影视中
![image](https://github.com/jadehh/TVSpider/assets/20532462/cf600641-a8d1-42a9-949d-dab013d3a12b)

见- https://github.com/jadehh/TVSpider/blob/main/json/TVBox.json

**Comment by jadehh** [comment]
你有好的线路也可以发来看看

**Comment by woshishiq1** [comment]
[360.zip](https://github.com/jadehh/TVSpider/files/14967258/360.zip)

**Comment by jadehh** [comment]
```js
const res = await this.http.post('https:///////////xmflv.js', data, {
            headers: {
                Origin: 'https://jx.xmflv.com',
                'Content-Type': 'application/x-www-form-urlencoded',
            },
  });
```
> 你这段怎么没有解析地址啊

**Comment by woshishiq1** [comment]
不是我的服务器，别人的服务器地址，不好分享

**Comment by jadehh** [comment]
荐片猫影视应该无法实现播放吧，猫不支持FTP格式的播放链接

**Comment by jadehh** [comment]
修复360影视在猫影视无法播放的bug
```
let sniffUrlList = ["https://jx.xmflv.com/?url=", "https://jx.quankan.app/?url=","https://jx.yparse.com/index.php?url="]
```
> 目前尝试了三种解析方式，后面只维护三种，如果有更稳定的解析方式可以添加,猫影视无法像TV一样选择聚众解析节点，所以固定三种方式，返回成功的URL。
