### ISSUE TITLE
你好。请教一下tvbox js一些问题

### ISSUE THREAD

**Issue by fdsa123q** [jadehh/TVSpider#47]
提交post,字符串带换行符号
例如:params='ABC\nEFG';
我抓包真实发送却是"ABC\nEFG"  带引号而且\n没直接展示换行
正确的发送数据是:
ABC
EFG

**Comment by jadehh** [comment]
JS中有特殊符号要用\\, 如"\"ABC\\nEFG\"", Post请求具体要看请求体格式
```js
 if (postType == 'form') 
  {
     headers['Content-Type'] = 'application/x-www-form-urlencoded';
     if (data != null) {
       data = qs.stringify(data, {encode: false});
       }
     } 
       else if (postType == 'form-data') {
         headers['Content-Type'] = 'multipart/form-data';
         data = toFormData(data);
  }
```

**Comment by fdsa123q** [comment]
附上源码。如果可以麻烦看下。里面的CatVodOpen能正常运行
外面的tvbox 提交就出现我说的。\\n也没用。播放端是fongmi的TVbox
[tiantian.zip](https://github.com/jadehh/TVSpider/files/14971504/tiantian.zip)

**Comment by jadehh** [comment]
TV无法正常运行具体是哪个接口没法用还是说所有接口都没法用

**Comment by fdsa123q** [comment]
所有接口post的数据。会带双引号发送出去换行符没用。协议头已经添加了。也不知道是不是tvbox的bug还是我没写正确

**Comment by fdsa123q** [comment]
自行解决了，        
method: get ? 'get' : 'post',
        headers: headers,
        body: p,  改body:p

**Comment by jadehh** [comment]
好的，建议还是TV和CatVodOpen用一份代码，不然维护成本太大。
