### ISSUE TITLE
tvbox源 ads加入4GTV 去廣規則

### ISSUE THREAD

**Issue by kai456789** [jadehh/TVSpider#73]
會看4GTV的直播源

可否在ads 加入下列網域  才能用影視嗅探4GTV

 "ads": [
    "static-mozai.4gtv.tv",
    "s3t3d2y8.afcdn.net",
  "4gtvfreepcvod-cds.cdn.hinet.net"
  ]

**Comment by jadehh** [comment]
可以修改json/TVBox.json基础配置文件中加入，然后提交。
