### ISSUE TITLE
workflow 提交私库失败

### ISSUE THREAD

**Issue by ufo888999** [jadehh/TVSpider#75]
毛影视GitHub链接要私库才有效

**Comment by jadehh** [comment]
[见Wiki](https://github.com/jadehh/TVSpider/wiki/TV-Spider-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)
Clone代码根据要求提交到自己的私仓中，或者直接复制到自己的私仓中

**Comment by deionCube** [comment]
Push to branch js
remote: Repository not found.
fatal: repository 'https://github.com/***.git/' not found

**Comment by ufo888999** [comment]
私人仓库失败，fork项目没问题
Run ad-m/github-push-action@master
Push to branch js
remote: Repository not found.
fatal: repository 'https://github.com/***.git/' not found
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:5[14](https://github.com/deionCube/jadehh1/actions/runs/8827391307/job/24234588834#step:7:15):28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 128
}

**Comment by jadehh** [comment]
检查代提交的私仓库是否存在

**Comment by ufo888999** [comment]
公开仓库没问题，私有仓库就出错，毛影视GitHub只支持私库

**Comment by jadehh** [comment]
`fatal: repository 'https://github.com/***.git/' not found`,这不是私仓地址错了吗

**Comment by ufo888999** [comment]
githubpath设置ufo888999/TVSpider 这个个fork的可以 ufo888999/TV是私有仓库就会报上面的错误

**Comment by deionCube** [comment]
大佬 是私有仓库不成功，爆错误啊，猫影视的github://链接需要是私库

**Comment by ufo888999** [comment]
大佬 是私有仓库不成功，爆错误啊，猫影视的github://Token@github.com/ufo888999/TV/dist/index.js.md5需要私有仓库库才可以

**Comment by jadehh** [comment]
你应该是在ufo888999/TVSpider，这个仓库中设置你私仓的地址，而不是设置你当前的仓库地址，这样可以在Actions中看到你的错误记录。

**Comment by ufo888999** [comment]
Run ad-m/github-push-action@master
Push to branch js
remote: Repository not found.
fatal: repository 'https://github.com/***.git/' not found
Error: Invalid exit code: 128
at ChildProcess. (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
at ChildProcess.emit (node:events:5[14](https://github.com/deionCube/jadehh1/actions/runs/8827391307/job/24234588834#step:7:15):28)
at maybeClose (node:internal/child_process:1105:16)
at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
code: 128
}
即使爆这错误

**Comment by jadehh** [comment]
![image](https://github.com/jadehh/TVSpider/assets/20532462/d43ea11e-813f-44e8-a4b1-cdb29b838bb2)
我这个Gitee地址是私仓是能够正常提交的

**Comment by ufo888999** [comment]
报错的我都 删了 githubpath改成ufo888999/TV私有库地址就会报错 gitee没问题 你可以试试

**Comment by jadehh** [comment]
我没你GitHub Token试不了的，那你用Gitee的私仓吧，把Github的都删了

**Comment by deionCube** [comment]
你用你的私库可以？

**Comment by jadehh** [comment]
> 你用你的私库可以？

我用的Gitee的私仓是没问题的

**Comment by jadehh** [comment]
修改了自动发布的脚本，规范了一些参数，详情见[TV-Spider-使用教程](https://github.com/jadehh/TVSpider/wiki/TV-Spider-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)。
使用其他账号测试了是能够同步到私仓当中的。可以查看[jiandehui/TVSpider]。(https://github.com/jiandehui/TVSpider/actions/runs/8864681402/job/24340118007) Actions的执行流程
![image](https://github.com/jadehh/TVSpider/assets/20532462/6550f551-fdbe-41d8-a7ad-f0cf35738411)
