### ISSUE TITLE
workflow - atomic transaction failed

### ISSUE THREAD

**Issue by howard868** [jadehh/TVSpider#76]
Push to branch js
To https://github.com/***.git
 ! [remote rejected] HEAD -> js (atomic transaction failed)
 ! [remote rejected] V1.0.3.8 -> V1.0.3.8 (refusing to allow a GitHub App to create or update workflow `.github/workflows/release.yaml` without `workflows` permission)

但是我的token已经给workflow权限了啊，怎么还是不行？

**Comment by jadehh** [comment]
![1714218630071](https://github.com/jadehh/TVSpider/assets/20532462/54c61d0b-4bb7-44d6-a5fd-ea049e7e5ca3)
Gitee部分是正常的，Github不正常
以下部分是我自己的部分，好像这部分确实有问题，过段时间再做个完整的测试
![image](https://github.com/jadehh/TVSpider/assets/20532462/3cd630fe-3b9d-4b1e-aa66-3c0e0afc068a)

**Comment by howard868** [comment]
好的 谢谢

**Comment by jadehh** [comment]
这个议题见 #75 ，先关了
