### ISSUE TITLE
TVBox看不了

### ISSUE THREAD

**Issue by howard868** [jadehh/TVSpider#77]
用了这个配置https://gh.con.sh/https://raw.githubusercontent.com/jadehh/TVSpider/js/tv_config.json
配置加载成功了 但是看不到任何视频 也搜索不到任何视频 用TVBox或者影视仓都不行

**Comment by jadehh** [comment]
我这边用的影视测的是正常的
![image](https://github.com/jadehh/TVSpider/assets/20532462/cf1ffe56-67eb-4c31-aa1a-2124d0a95f1e)
![image](https://github.com/jadehh/TVSpider/assets/20532462/63147c92-b934-4d0a-abdb-dada85d76339)
![image](https://github.com/jadehh/TVSpider/assets/20532462/733fbc89-77d4-491a-80dc-3cdc64fdc922)

**Comment by howard868** [comment]
这是什么版本的tvbox？Fongmi的吗？

**Comment by jadehh** [comment]
> 这是什么版本的tvbox？Fongmi的吗？

是的，只测试过蜂蜜的TV

**Comment by howard868** [comment]
> > 这是什么版本的tvbox？Fongmi的吗？
> 
> 是的，只测试过蜂蜜的TV

我刚下载了蜂蜜版的，的确可以用。白版，黑版还有影视仓是用不了的。那就用蜂蜜好了

**Comment by jadehh** [comment]
如果需要其他的 app 适配，可以提供提新 issue 包括测试 app 下载地址➕正常的 config 文件
