### ISSUE TITLE
TVBox takagen99版

### ISSUE THREAD

**Issue by howard868** [jadehh/TVSpider#78]
可不可以支持这个takagen99版本的tvbox？

App下载链接：
https://u.pcloud.link/publink/show?code=XZWulb0Z4MoLmGSysVSfQ6T0Lf0Wv5L0k6I7

可用的json:
https://raw.githubusercontent.com/gaotianliuyun/gao/master/0827.json

**Comment by howard868** [comment]
大佬没时间的话就不用折腾匹配这个app了 现在觉得蜂蜜版的好像更流畅些

**Comment by jadehh** [comment]
他这个是不是不支持js爬虫

**Comment by jadehh** [comment]
暂时还是不考虑其他App了，遇到部分源无法解析的，还是要看App源码进行调试，未来还是只考虑蜂蜜TV了。
