### ISSUE TITLE
请教新版CatVodOpen怎么使用啊。麻烦了谢谢

### ISSUE THREAD

**Issue by MINGERTAI** [jadehh/TVSpider#85]
请教新版CatVodOpen怎么使用啊。麻烦了谢谢
仓库没有这个文件夹TVSpider/dist/，求教

**Comment by xhybb** [comment]
![屏幕截图 2024-05-01 224403](https://github.com/jadehh/TVSpider/assets/19210186/3cbcf666-7331-4cd0-8ae5-6afd5e37e6d5)

fork到自己仓库时去掉这个勾

**Comment by jadehh** [comment]
看wikis可以利用workflows自动发布

**Comment by MINGERTAI** [comment]
请教，怎么添加tvbox源，到您这个项目fork自己仓库中的项目，actions自动变更为猫影视的源
