### ISSUE TITLE
项目怎么跑起来  新手

### ISSUE THREAD

**Issue by Hululu007** [jadehh/TVSpider#89]
第一次接触这个，新手要怎么把项目运行起来；还有就是在执行 python build.py这个的时候，报错了：
PS E:\TVSpider> python build.py
Traceback (most recent call last):
  File "build.py", line 11, in <module>
    from jade import str_to_bool, CreateSavePath, GetLastDir, GetTimeStamp
ModuleNotFoundError: No module named 'jade'
这个不知道该怎么办

**Comment by Hululu007** [comment]
执行了python build.py之后,可以生成tv_config.json和 spider下面的js文件 ，但dist文件目录怎么生成呢，主要是想怎么打包生成，在之情npm install的时候报错了，具体不知道啥原因 
[2024-05-02T10_54_27_783Z-debug-0.log](https://github.com/jadehh/TVSpider/files/15187175/2024-05-02T10_54_27_783Z-debug-0.log)

**Comment by jadehh** [comment]
dist分支是通过 cd nodejs 文件夹下 执行 node build 生成的。具体看下 workflows 下的脚本。里面有完整的命令。

**Comment by jadehh** [comment]
大概看了下你的日志，: Could not find any Visual Studio installation to use 环境问题吧。

**Comment by Hululu007** [comment]
估计是环境问题  你那边搭配的什么环境 方便说一说么 谢谢

**Comment by jadehh** [comment]
> 估计是环境问题 你那边搭配的什么环境 方便说一说么 谢谢

我这边是安装了Visual Sudio，如果环境有问题，建议还是换成Linux或者是直接通过Workflows直接生成dist分支。

**Comment by Hululu007** [comment]
那估计是了 我去安装vs试试
