### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by MINGERTAI** [jadehh/TVSpider#94]
我在js分支上open_config.json添加了源，也在js文件夹内添加相应的.js文件，也在ｍain上js文件夹内添加相应的.js但是actions执行完成，完全没有把添加的几个源，加入到猫影视那，请求帮助，谢谢

**Comment by jadehh** [comment]
自动发布是通过 build.py 文件生成，通过解析 js 文件，获取到正确的源名称，具体可以看下写的 js 风格。如果命名不规范是无法写入到 config 文件的。可以按照固定的风格改写 js 文件

**Comment by MINGERTAI** [comment]
谢谢
